### ISSUE TITLE
Merging Azata with Bard gives Aeon spells

### ISSUE THREAD

**Issue by arshesney** [vikigenius/SpellbookMerge#1]
I've tested by respecing with the respec mod, don't have an earlier save to test it at the proper moment.

Selected to merge spellbooks as Bard when picking Azata path, caster level scales correctly, but spells added are from Aeon.

**Comment by vikigenius** [comment]
Ah, must have added the wrong blueprint for Azata spellbook I think, will fix it soon

**Comment by vikigenius** [comment]
Can you check this one? I fixed it. If it fixes the bug for you, I will create a new release. 

[SpellbookMerge.zip](https://github.com/vikigenius/SpellbookMerge/files/7475540/SpellbookMerge.zip)

**Comment by arshesney** [comment]
With this build spellbooks do not merge at all, Azata just vanishes, CL stays 20 and noi mythic spells are gained.

I'll attach logs if they can help you
[logs.zip](https://github.com/vikigenius/SpellbookMerge/files/7476340/logs.zip)
.

**Comment by vikigenius** [comment]
Yeah, I found the issue. Looks like the game has two different Azata spell list blueprints. I chose the wrong one.

**Comment by vikigenius** [comment]
The new release should fix this. You can reopen this if the issue persists.
