### ISSUE TITLE
Azata Hero Never Surrender Cause All Spellbooks Added

### ISSUE THREAD

**Issue by ForbAvalon** [vikigenius/SpellbookMerge#16]
As title says ,  I used sword saints merged azata mysticbooks , when i use lv7 spell hero never surrender I will get all spellbooks added to my charactor

**Comment by ForbAvalon** [comment]
And i test skald and bard will cause this problem.
My game version is 1.1.7f

**Comment by vikigenius** [comment]
Duplicate of https://github.com/vikigenius/SpellbookMerge/issues/12
