### ISSUE TITLE
Merge not showing

### ISSUE THREAD

**Issue by Tyrroth** [vikigenius/SpellbookMerge#24]
Hello,
Tried merging (on an older safe just before Sword of Valor) Azata and Demon with Wizard (Thassilon Specialist), but it doesn't work. Can't chose the spellbook of the wizard. Is this a bug or is Thassilon Specialist not yet supported?

Tested with ToyBox and Arcanist, that works.

Tested with 2.0.0z and 1.7

**Comment by vikigenius** [comment]
Likely that Thassilon Specialist has a separate spellbook and is thus not supported yet.

**Comment by Tyrroth** [comment]
I was playing around with it and came to the same conclusion. Thanks for the effort, though.
