### ISSUE TITLE
Believe in yourself missing on respec after azata merge

### ISSUE THREAD

**Issue by bje259** [vikigenius/SpellbookMerge#7]
I'm not sure if the azata spell believe in yourself is coded differently than the others, but I recently did a respec and merged my spellbook magus and azata spellbooks during the mythic level up process and I had azata spells up to level 6 (currently caster level 19 after the merge) but was missing this level 3 spell.

I had done a respec with a previous version and the spell showed up as expected.  Let me know if there is anything I can get you to help.  I did try reloading (full game exit), changing areas, etc.

**Comment by vikigenius** [comment]
> I had done a respec with a previous version and the spell showed up as expected.

Can you clarify this? You mean previous version of my mod? If so, which version?

**Comment by vikigenius** [comment]
Also note that one of the discord comment says:

> yeah believe in yourself is not technically on the Azata spell list, it is added to the book externally at the end of Act 3 depending on how you played the act

So this is likely very tricky to solve, because the Azata spellbook technically no longer exists once you merge.

I will have to look into if Angel has any similar spells,and if so how is the in game code handling it. If you know any Angel/Lich spells that are similar, let me know so that I can debug.

**Comment by bje259** [comment]
I think I know what it is based on your notes. When I installed the mod the first time (version 1.1.1), I was already ranked up higher in Azata.  I used the respec mod to reset my mythic levels, then I installed this mod and proceeded to rank up including the merged spellbook which at that time included believe in yourself.  I did the same thing this time, but it was on a save where I was only rank 3 of azata before resetting my mythic rank.  I found the feature in toybox that grants believe in yourself, and added it manually and it was added to my merged spellbook.  It's possible that if I had would have received that believe in yourself feature naturally by the game at a higher mythic rank.  If I get a chance to test that, I'll let you know!

**Comment by bje259** [comment]
So I can confirm that this spell is added by a feature "AzataForSpellsGoodFeature" which is a story trigger (my first save must have already triggered).  I still haven't come across the exact point in act 3 that triggers it, but what I can confirm is that it appropriately adds the spell to the merged spellbook as expected.  I think we can close this issue as I think the worst case here is that people are confused by the timing of when they receive the spell.  Unless that's something you want to alter, I think everything is working fine.

Thanks for your response and the time spent creating this mod!  Will let you know if I run into anything else!
